export enum WiwaErrorCode {
    UNKNOWN = 'UNKNOWN',
    NOT_FOUND = 'NOT_FOUND',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    APPLICATION_IMAGE_NOT_SUPPORTED = 'APPLICATION_IMAGE_NOT_SUPPORTED',
    APPLICATION_PROPERTY_NOT_FOUND = 'APPLICATION_PROPERTY_NOT_FOUND',
    AUTHORITY_NOT_FOUND = 'AUTHORITY_NOT_FOUND',
    GDPR = 'GDPR',
    INVALID_CAPTCHA = 'INVALID_CAPTCHA',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    UNSUPPORTED_VALIDATION_TOKEN = 'UNSUPPORTED_VALIDATION_TOKEN',
    USER_EMAIL_IS_USED = 'USER_EMAIL_IS_USED',
    USER_IS_DISABLED = 'USER_IS_DISABLED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_USERNAME_IS_USED = 'USER_USERNAME_IS_USED'
}

export interface WiwaError {
    code: WiwaErrorCode,
    message: string,
    timestamp: string
}
